[debug] [2020-12-22T16:52:17.329Z] ----------------------------------------------------------------------
[debug] [2020-12-22T16:52:17.331Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2020-12-22T16:52:17.331Z] CLI Version:   9.0.1
[debug] [2020-12-22T16:52:17.332Z] Platform:      darwin
[debug] [2020-12-22T16:52:17.332Z] Node Version:  v12.16.1
[debug] [2020-12-22T16:52:17.333Z] Time:          Tue Dec 22 2020 22:22:17 GMT+0530 (India Standard Time)
[debug] [2020-12-22T16:52:17.333Z] ----------------------------------------------------------------------
[debug] [2020-12-22T16:52:17.333Z] 
[debug] [2020-12-22T16:52:17.365Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-12-22T16:52:17.366Z] > authorizing via signed-in user
[debug] [2020-12-22T16:52:17.366Z] [iam] checking project netflix-clone-3fd3d for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2020-12-22T16:52:17.369Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2020-12-22T16:52:17.369Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-12-22T16:52:17.793Z] <<< HTTP RESPONSE 200 {"pragma":"no-cache","cache-control":"no-cache, no-store, max-age=0, must-revalidate","date":"Tue, 22 Dec 2020 16:52:17 GMT","expires":"Mon, 01 Jan 1990 00:00:00 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-22T16:52:17.828Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/netflix-clone-3fd3d:testIamPermissions  
 {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2020-12-22T16:52:19.202Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Tue, 22 Dec 2020 16:52:19 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=1218","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-22T16:52:19.204Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/netflix-clone-3fd3d  
 
[debug] [2020-12-22T16:52:49.217Z] Server Error. ETIMEDOUT
[debug] [2020-12-22T16:52:49.570Z] FirebaseError: Server Error. ETIMEDOUT
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:32:31)
    at self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[error] 
[error] Error: Failed to get Firebase project netflix-clone-3fd3d. Please make sure the project exists and your account has permission to access it.
